AllCops:
  TargetRubyVersion: 3.1.0
  Include:
    - 'bin/**/*.rb'
    - 'lib/**/*.rb'
    - 'rspec/**/*.rb'

Layout/SpaceInsideStringInterpolation:
  Enabled: false

Metrics/BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 120

Metrics/LineLength:
  Max: 120

Naming/AccessorMethodName:
  Enabled: false

Style/ClassVars:
  Exclude:
    - 'lib/model_base.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
