AllCops:
  TargetRubyVersion: 3.1.0
  Exclude:
    - 'db/**'

Layout/SpaceInsideStringInterpolation:
  Enabled: false

Metrics/BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 120

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
