#!/usr/bin/env ruby

if ARGV.empty?
  require_relative 'bin/main'
else
  require_relative 'configus/environment'

  ARGV.each do |arg|
    case arg
    when 'db::drop'
      Database.drop
    when 'db:create'
      Database.setup
    when 'db:seed'
      Seeds.seed
    when 'c'
      ARGV.clear
      IRB.start
    else
      puts "Неизвестная команда: #{arg}"
    end
  end
end

# Отправьте уведомление
# system('osascript -e \'display notification "Ваше приложение запущено" with title "Cramming"\'')
